[package]
name = "lean-scheme"
version = "0.1"
lean_version = "3.4.2"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover/mathlib", rev = "1f4f2e421f30390efca68776a4850f471cc72169"}
